# CONFIGURACION FECHA Y HORA
logging:
  pattern:
    dateformat: dd-MM-yyyy hh:mm:ss

# CONFIGURACION CONEXION MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tienda_libros_prod
    username: GEAT
    password: programador

  # CONFIGURACION PARA MOSTRAR SENTENCIAS SQL
  jpa:
    show-sql: true
